[package]
name = "stress-test"
version = "0.1.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"

[workspace]

[dependencies]
flize = "=3.2.0"
crossbeam-epoch = { path = "../../../crossbeam-epoch" }
