[package]
name = "ci"
version = "0.1.0"
edition = "2018"
publish = false

[workspace]

[dependencies]
toml_edit = "0.1.3"

[[bin]]
name = "remove-dev-dependencies"
path = "remove-dev-dependencies.rs"
